= Configuration

This page discusses all the ways in which Tapestry can be configured. Tapestry applications are configured almost entirely using Java, with very little XML at all.

== XML configuration (web.xml)
Tapestry runs on top of the standard Java Servlet API. To the servlet container, such as Tomcat, Tapestry appears as a _servlet filter_.
This gives Tapestry great flexibility in matching URLs without requiring lots of XML configuration.

Although most configuration is done with Java, a small but necessary amount of configuration occurs inside the servlet deployment descriptor, `WEB-INF/web.xml`.
Most of the configuration is boilerplate, nearly the same for all applications.

.web.xml (partial)
[source,xml]
----
<!DOCTYPE web-app
      PUBLIC "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
      "http://java.sun.com/dtd/web-app_2_3.dtd">
<web-app>
    <display-name>My Tapestry Application</display-name>
    <context-param>
        <param-name>tapestry.app-package</param-name>
        <param-value>org.example.myapp</param-value>
    </context-param>
    <filter>
        <filter-name>app</filter-name>
        <filter-class>org.apache.tapestry5.TapestryFilter</filter-class> <1>
    </filter>
    <filter-mapping>
        <filter-name>app</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
</web-app>
----
<1> Or org.apache.tapestry5.*http*.TapestryFilter if you're using tapestry-http without tapestry-core

The application-specific part, the `tapestry.app-package` context parameter, provides your application's root package name.
Tapestry uses this to locate your page and component classes.
It expects page classes in the pages sub-package and components in the components sub-package.
In the example above, page classes will be stored in the `org.example.myapp.pages` package (or in sub-packages below).
Likewise, component classes will be stored in the `org.example.myapp.components` package.

By convention, the filter name (`filter-name`) is almost always `app`, but you can use any name you want.
Tapestry uses this to determine what _module class_ name to look for (see below).


.Tapestry Requests vs. Container Requests
****
The Tapestry filter matches all the requests that apply to Tapestry, and passes the rest off to the servlet container.
In situations where there would be a naming conflict, actual files inside the web application take precedence over Tapestry pages.

Tapestry recognizes the root URL, where the servlet path is simply "/", and renders the application page "Index", if it exists.
****

== Your Application's Module Class
Main Article: xref:tapestry-ioc-configuration.adoc

Most other configuration occurs inside your application's module class.
The application module class will often define new services, provide overrides of services, or make contributions to service configurations.

Tapestry looks for your application module class in the services package (under the root package) of your application.
It capitalizes the `<filter-name>` and appends `Module`.
In the previous example, because the filter name was `app` and the application's root package name is `org.example.myapp`, the module class would be `org.example.myapp.services.AppModule`.

If such a class exists, it is added to the IoC Registry.
It is not an error for your application to not have a module class, though any non-trivial application will have one.

Your application module class (usually `AppModule.java`) will typically override some of Tapestry's default, or "factory", symbols, by contributing overrides to the ApplicationDefaults service configuration. For example:

.AppModule.java
[source,java]
----
public class AppModule
{
  public static void contributeApplicationDefaults(MappedConfiguration<String,String> configuration)
  {
    configuration.add(SymbolConstants.SUPPORTED_LOCALES, "en,fr,de");
    configuration.add(SymbolConstants.FILE_CHECK_INTERVAL, "10 m");
  }
}
----

== Configuration Symbol Names
Main Article: xref:symbols.adoc[]

Many of Tapestry's built-in services (some of which are not even public) are configured via symbols.
These symbols can be overridden by contributing to the ApplicationDefaults service configuration, or by placing a `<context-param>` element into the application's `web.xml`, or on the command line by defining JVM System Properties with the `-D` command line option.

These symbols are always defined in terms of strings, and those strings are coerced to the appropriate type (a number, a boolean, etc.).
Of special note are _time intervals_, which are specified in a particular format (see javadoc::org.apache.tapestry5.ioc.util.TimeInterval[]).

Most of these symbols have a constant defined in the javadoc:org.apache.tapestry5.SymbolConstants[] class.
//, while others are in the IOCSymbols class (since 5.2.2..
Use the symbol name (`tapestry.*`) for JVM System Properties with the `-D` option, and use the constant (in bold below) from within your Java classes (e.g. `AppModule.java`).

////
tapestry.app-catalog | javadoc:org.apache.tapestry5.SymbolConstants#APPLICATION_CATALOG[]:: 
Since 5.1 +
The location of the global application message catalog, the default is `context:WEB-INF/app-name.properties`.
////

tapestry.application-folder | javadoc:org.apache.tapestry5.SymbolConstants#APPLICATION_FOLDER[]::
Since 5.3.1 +
The folder, of the context, in which the Tapestry application executes.
By default this is blank, meaning the Tapestry application executes in the root of the web application context.
Setting this value allows the Tapestry application to be segregated into a folder, which can be useful when Tapestry is executed inside a web application with other servlets or filters.

tapestry.application-version | javadoc:org.apache.tapestry5.SymbolConstants#APPLICATION_VERSION[]::
Since 5.1.0.0 +
The version of the application, which is incorporated into URLs for context and classpath assets.
xref:assets.adoc[Assets] may be xref:response-compression.adoc[compressed], and will have far-future expiration headers; they will be aggressively cached by the client web browser.
You should change the application version on each new deployment of the application (that is, any time assets in the context change), to force clients to re-download changed versions of files.
If you do not specify an application version, a _random_ one will be assigned on every deployment (which is good for development but very bad for production).

tapestry.asset-url-fully-qualified | javadoc:org.apache.tapestry5.SymbolConstants#ASSET_URL_FULL_QUALIFIED[]:: 
Since 5.3.1 +
A boolean value to indicate whether asset URLs should be fully qualified in the rendered page.
This defaults to `false` (not fully qualified).

tapestry.asset-path-prefix | javadoc:org.apache.tapestry5.SymbolConstants#ASSET_PATH_PREFIX[]::
Since 5.3.1 +
The prefix to be used for all asset paths. This should start and end with a slash ("/").
By default this is `/assets/`.

tapestry.blackbird-enabled | javadoc:org.apache.tapestry5.SymbolConstants#BLACKBIRD_ENABLED[]::
Since 5.2.0 +
A flag (`true` or `false`).
When `false` the Blackbird JavaScript console will be disabled.
Defaults to `true`.
Deprecated since 5.3 The client-side BlackBird console has been removed.

// === tapestry.bootstrap-root
// Added in 5.4
// *SymbolConstants.BOOTSTRAP_ROOT* –
// The root asset path for Twitter Bootstrap; if your application uses a modified version of Bootstrap, you can override this symbol to have Tapestry automatically use your version.
// The value should be a path to a folder (under "classpath:" or "context:") and should not include a trailing slash.

// === tapestry.font-awesome-root
// Added in 5.5.0
// *SymbolConstants.FONT_AWESOME_ROOT* – The root asset path for FontAwesome; if your application uses a modified version of it, you can override this symbol to have Tapestry automatically use your version.
// The value should be a path to a folder (under "classpath:" or "context:") and should not include a trailing slash.

////
tapestry.charset | javadoc:org.apache.tapestry5.SymbolConstants#CHARSET[]::
The character encoding used when generating output (or parsing input).
The default is "UTF-8".
See xref:content-type-and-markup.adoc[] for more details.
////

tapestry.clustered-sessions | javadoc:org.apache.tapestry5.SymbolConstants#CLUSTERED_SESSIONS[]::
Since 5.3.1 +
If `true` then at the end of each request the javadoc:org.apache.tapestry5.services.SessionPersistedObjectAnalyzer[] will be called on each session persisted object that was accessed during the request.
The default is "true", to preserve 5.2 behavior.
For non-clustered applications (the majority), this value should be overridden to `false`.

tapestry.combine-scripts | javadoc:org.apache.tapestry5.SymbolConstants#COMBINE_SCRIPTS[]::
Since 5.1.0.2 +
If `true`, then Tapestry will combine (or "aggregate") the individual JavaScript libraries within a JavaScript stack; this reduces the number of requests from the client to the server, as the client can cache the combined JavaScript files locally (and will not need to re-download them on subsequent pages).
The implementation of this changed significantly between Tapestry 5.1 and 5.2.
Defaults to `true` in production mode.

// === tapestry.compact-json
// Added in 5.2
// *SymbolConstants.COMPACT_JSON* – If "true", then JSON page initialization content is compressed; if "false" then extra white space is added (pretty printing). Defaults to "true" in production mode.

// === tapestry.compatibility.unknown-component-id-check-enabled
// Added in 5.3
// Deprecated since 5.3
// *SymbolConstants.UNKNOWN_COMPONENT_ID_CHECK_ENABLED* – When enabled, Tapestry will check that component ids referenced in event handler method names (or the @OnEvent annotation) match up against components in the container's template. The default is true, but applications upgraded form Tapestry 5.2 may want to set this to false, to keep pages from failing due to the presence of such dead code.

// === tapestry.component-render-tracing-enabled
// SymbolConstants.COMPONENT_RENDER_TRACING_ENABLED –
// Starting with version 5.3, if "true" then Tapestry will emit rendering comments for all requests; these are comments (such as <!--BEGIN Index:loop (context:Index.tml, line 15)-->) that can assist you in debugging markup output on the client-side. This will significantly increase the size of the rendered markup, but can be very helpful with complex layouts to determine which component was responsible for which portion of the rendered page. (To turn on rendering comments only for a particular request, add the query parameter t:component-trace=true to the URL.)

tapestry.compress-whitespace | javadoc:org.apache.tapestry5.SymbolConstants#COMPRESS_WHITESPACE[version={javadoc-version}]::
Since 5.0 +
A flag (`true` or `false`). When `true` (the default) whitespace in component templates is compressed by default (this can be fine-tuned using the standard `xml:space` attribute on an element in the template).
When this flag is false, then whitespace is retained by default (but can still be overridden).
See xref:component-templates.adoc[] for details.

// === tapestry.module-path-prefix
// Added in 5.4
// SymbolConstants.MODULE_PATH_PREFIX – 
// Prefix used for all module resources.
// This may contain slashes, but should not begin or end with one.
// Tapestry will create two Dispatchers from this: one for normal modules, the other for GZip compressed modules (by appending ".gz" to this value).

// === tapestry.context-path
// Added in 5.4
// SymbolConstants.CONTEXT_PATH –
// Identifies the context path of the application, as determined from ServletContext.getContextPath() method. This is either a blank string or a string that starts with a slash but does not end with one.

// === tapestry.datepicker
// Added in 5.2
// SymbolConstants.DATEPICKER – The path to the assets of the embedded DatePicker component

tapestry.default-cookie-max-age | javadoc:org.apache.tapestry5.SymbolConstants#COOKIE_MAX_AGE[]::
Since 5.2.0 +
The default time interval that cookies created by Tapestry will be kept in the client web browser.
Primarily, this is used with a cookie that exists to track the preferred user locale.
The default value is "7 d" (7 days; see javadoc:org.apache.tapestry5.ioc.util.TimeInterval[] formats).

tapestry.enable-minification | javadoc:org.apache.tapestry5.SymbolConstants#MINIFICATION_ENABLED[]::
Since 5.3.0 +
If `true`, then resources (individually or when aggregated into stacks) will be minimized via the javadoc:org.apache.tapestry5.services.assets.ResourceMinimizer service.
If `false`, then minification is disabled.
The default is `true` in production mode, `false` otherwise. +
+
Note that Tapestry's default implementation of ResourceMinimizer does nothing; minification is provided by add-on libraries.
See xref:assets.adoc[] for details.

tapestry.default-stylesheet | javadoc:org.apache.tapestry5.SymbolConstants#DEFAULT_STYLESHEET[]::
Since 5.2.0 +
The default stylesheet automatically injected into every rendered HTML page.
Many Tapestry components assume that this stylesheet is available.
All the classes defined in the stylesheet are prefixed with `t-`.
The exact contents of the stylesheet are subject to change at `ny time (they are considered internal), so replacing the stylesheet, rather than overriding selected rules within it, entails some risk.

tapestry.encode-locale-into-path | javadoc:org.apache.tapestry5.SymbolConstants#ENCODE_LOCALE_INTO_PATH[]::
Since 5.1.0.1 +
If `true` (the default), then the javadoc:org.apache.tapestry5.services.PersistentLocale[] will be encoded into URLs by the javadoc:org.apache.tapestry5.services.ComponentEventLinkEncoder[] service.
If overridden to `false` this does not occur, but you should provide a javadoc:org.apache.tapestry5.services.LinkCreationListener2[] (registered with the javadoc:org.apache.tapestry5.services.LinkCreationHub[]) in order to add the locale as a query parameter (or provide some alternate means of persisting the locale between requests).
See xref:localization.adoc[] for more details on localization.

tapestry.execution-mode | javadoc:org.apache.tapestry5.SymbolConstants#EXECUTION_MODE[]::
Since 5.3.1 +
The execution mode. See <<Setting Execution Modes>> below.

tapestry.file-check-interval | javadoc:org.apache.tapestry5.SymbolConstants#FILE_CHECK_INTERVAL[]::
Since 5.0 +
Time interval between file system checks.
During a file system check, only a single thread is active (all others are blocked) and any files loaded are checked for changes (this is part of Tapestry's xref:class-reloading.adoc[] mechanism). +
The default is "1 s" (one second; see javadoc:org.apache.tapestry5.ioc.util.TimeInterval[]), and is usually overridden with a higher value in production (say, between one and five minutes).

tapestry.file-check-update-timeout | javadoc:org.apache.tapestry5.SymbolConstants#FILE_CHECK_UPDATE_TIMEOUT[]::
Since 5.0 +
Time interval that Tapestry will wait to obtain the exclusive lock needed for a file check.
If the exclusive lock can't be obtained in that amount of time, the request will proceed normally (without the check), but each successive request will attempt to get the lock and perform the check until successful. +
The default is "50 ms" (50 milliseconds; see javadoc:org.apache.tapestry5.ioc.util.TimeInterval[]).

tapestry.force-absolute-uris | javadoc:org.apache.tapestry5.SymbolConstants#FORCE_ABSOLUTE_URIS[]::
Since 5.0 +
When `false` (the default), Tapestry will attempt to optimize URIs that it generates, using relative URIs when such URIs are shorter than absolute URIs.
When `true`, all URIs will be absolute URIs (including the context path, and the complete path for the request). 

tapestry.gzip-compression-enabled | javadoc:org.apache.tapestry5.SymbolConstants#GZIP_COMPRESSION_ENABLED[]::
Since 5.1.0.0 +
Override to `false` to disable GZIP compression of dynamic Tapestry pages and static assets.

tapestry.hmac-passphrase | javadoc:org.apache.tapestry5.SymbolConstants#HMAC_PASSPHRASE[]::
Since 5.3.6 +
The plaintext phrase used to set the key for HMAC securing of serialized object data.
The default is blank, which causes a runtime alert and console error.
You should set this to a reasonably unique, private value, and ensure (in a cluster) that all servers use the same value – typically by making a contribution in your applications module class (normally AppModule.java).
See xref:security.adoc[] for details.

tapestry.hostname | javadoc:org.apache.tapestry5.SymbolConstants#HOSTNAME[]::
Since 5.3.0 +
The hostname that application should use when constructing an absolute URL.
The default is "", i.e. an empty string, in which case system will use `request.getServerName()`.
_Not_ the same as environment variable `HOSTNAME` (but you could contribute `$HOSTNAME` as the value to make it the same).

tapestry.hostport | javadoc:org.apache.tapestry5.SymbolConstants#HOSTPORT[]::
Since 5.3.0 +
The port that application should use when constructing an absolute URL.
The default is "0", which means to use the port value from the request.

tapestry.hostport-secure | javadoc:org.apache.tapestry5.SymbolConstants#HOSTPORT_SECURE[]::
Since 5.3.0 +
The secure (https) port that application should use when constructing an absolute URL.
The default is "0", i.e. use the value from the request.

tapestry.min-gzip-size | javadoc:org.apache.tapestry5.SymbolConstants#MIN_GZIP_SIZE[]::
Since 5.1.0.0 +
The minimum stream size necessary for Tapestry to use GZIP compression on the response stream. See xref:response-compression.adoc[] for more details.

tapestry.omit-generator-meta | javadoc:org.apache.tapestry5.SymbolConstants#OMIT_GENERATOR_META[]::
Since 5.1.0.0 +
If `true`, then the `<meta>` tag that Tapestry normally writes into the `<head>`, identifying the Tapestry version, will be omitted.
Use this when you do not wish to advertise your application's use of Tapestry.

tapestry.persistence-strategy | javadoc:org.apache.tapestry5.SymbolConstants#PERSISTENCE_STRATEGY[]::
Since 5.1.0.0 +
Identifies the default persistence strategy for all pages that do not provide an override.
The default is `session` (javadoc:org.apache.tapestry5.PersistenceConstants#SESSION[]).

tapestry.production-mode | javadoc:org.apache.tapestry5.SymbolConstants#PRODUCTION_MODE[]::
Since 5.0 +
A flag (`true` or `false`) indicating whether the application is running in production or in development.
The default is `true`, which means that runtime exceptions are not reported with full detail (only the root exception message is displayed, not the entire stack of exceptions, properties and other information shown in development mode).

tapestry.secure-enabled | javadoc:org.apache.tapestry5.SymbolConstants#SECURE_ENABLED[]::
Since 5.1.0.1 +
If `true`, then javadoc:org.apache.tapestry5.annotations.Secure[label=@Secure] annotations are honored; if `false`, no security checks or redirects take place.
This defaults to `tapestry.production-mode`, meaning that in development mode it will (by default) be disabled.
However, sites that are intended to be served only under HTTPS should set this to `false`. See xref:https.adoc[] for details.

tapestry.script-at-top | javadoc:org.apache.tapestry5.SymbolConstants#SCRIPTS_AT_TOP[]::
WARNING: Deprecated since 5.1.0.1. Scripts are now always at the top (see issue:544[]) +
Since 5.0.16 +
If `true`, then links for external JavaScript libraries are placed at the top of the document (just inside the `<body>` element).
If `false`, the default, then the libraries are placed at the bottom of the document.
Per-page initialization always goes at the bottom.

tapestry.start-page-name | javadoc:org.apache.tapestry5.SymbolConstants#START_PAGE_NAME[]::
Since 5.2.0 +
The logical name of the start page, the page that is rendered for the _root URL_.
This is normally "start".
This functionality is vestigial: it has been superseded by the use of Index pages.

tapestry.suppress-redirect-from-action-requests | javadoc:org.apache.tapestry5.SymbolConstants#SUPPRESS_REDIRECT_FROM_ACTION_REQUESTS[]::
Since 5.0 +
Normally, Tapestry responds to action requests (such as form submissions) by sending a client-side redirect to the rendering page.
This has a lot of benefits in terms of improving browser navigation, making sure URLs are bookmarkable, and so forth.
However, it has a cost: more data stored persistently in the session, and a double-request for each user action (one action request, one render request). +
Setting this symbol to `true` changes the Tapestry behavior to make it more like Tapestry 4: a markup response is sent directly for the action request, with no redirect in the middle.
This option should be used with care, and only in cases where you are certain that the benefits outweigh the disadvantages.
// Deprecated since 5.2
// Removed in 5.3

tapestry.supported-locales | javadoc:org.apache.tapestry5.SymbolConstants#SUPPORTED_LOCALES[]::
Since 5.0 +
A comma-separated list of supported locales.
Incoming requests as "narrowed" to one of these locales, based on closest match.
If no match can be found, the first locale in the list is treated as the default. +
The default is (currently) "en,it,es,zh_CN,pt_PT,de,ru,hr,fi_FI,sv_SE,fr_FR,da,pt_BR,ja,el".
As the community contributes new localizations of the necessary messages files, this list will expand.
Note that the Tapestry quickstart archetype overrides the factory default, forcing the application to be localized only for `en`.


== Setting Component Parameter Defaults
Added in 5.3
Some components, notably Grid, Pallete and Zone, have default parameter values specified in terms of symbols.
This means you can use these symbols to modify the defaults for all instances of such components in your application.
For example, you can set the default rows per page for all Grid instances by adding this to the contributeApplicationDefaults method in your application's module class (typically AppModule.java): `configuration.add(ComponentParameterConstants.GRID_ROWS_PER_PAGE, "15");`
See the complete list of such constants at ComponentParameterConstants.

== Configuring Ignored Paths
You may sometimes need to use Tapestry in concert with other servlets.
This can cause problems, since Tapestry (being a servlet filter) may see URLs intended for another servlet and attempt to process them.

The Servlet API does not provide Tapestry with any clues about what other servlets are available in the web application.
Instead, you must configure Tapestry to ignore paths intended for other servlets.

The javadoc:org.apache.tapestry5.internal.services.IgnoredPathsFilter[] service is the method for this kind of configuration.
Its configuration is an unordered collection of regular expression patterns.
A request whose path matches any of these patterns is *not* processed by Tapestry.

For example, say you are using http://getahead.org/dwr/[Direct Web Remoting].
You'll likely have the servlet path `/dwr` mapped to the Direct Web Remoting servlet.

You contribution would look like:

.AppModule.java (partial)
[source,java]
----
public static void contributeIgnoredPathsFilter(Configuration<String> configuration)
{
    configuration.add("/dwr/.*");
}
----

The regular expression matches any path that begins with `/dwr/`.

The regular expressions provided in the configuration are always compiled with case insensitivity enabled.

Also note that actual files in your web application (images, stylesheets, etc.) are always ignored by Tapestry.

== Configuring Content Type Mapping
The mapping from file type (by extension) to content type is typically done as part of your servlet-containers configuration.
Alternately, you may contribute to the javadoc:org.apache.tapestry5.internal.services.ResourceStreamer[] service's configuration.
This is a mapped configuration; it maps file extensions (such as "css" or "js") to content types (`text/css` or `text/javascript`) respectively.

== Setting Execution Modes

== Segregating Applications Into Folders
In many cases where Tapestry is being adopted into an existing web application (possibly written in Tapestry 4 or some other framework), it is nice to segregate the Tapestry application into its own folder, to avoid conflicts with the existing application or servlets.

Setting this up is in two parts:

* Modifying the configuration of the `<url-pattern>` for the Tapestry filter to match the specified folder.
* Identifying the folder name using a Tapestry symbol value contribution.

So, if you wanted to run the Tapestry application inside folder `t5app`, you would modify your `web.xml` indicate the use of the folder:

.web.xml (partial)
[source,xml]
----
<filter-mapping>
  <filter-name>app</filter-name>
  <url-pattern>/t5app/*</url-pattern>
</filter-mapping>
----

... and in your AppModule, you would inform Tapestry about the mapping change:

.AppModule.java
[source,java]
----
public class AppModule
{
    @Contribute(SymbolProvider.class)
    @ApplicationDefaults
    public static void applicationDefaults(MappedConfiguration<String, String> configuration)
    {
        configuration.add(SymbolConstants.APPLICATION_FOLDER, "t5app")
    }
}
----

NOTE: This extra mapping is unfortunately necessary, because the Servlet API does not provide a way for a servlet filter, such as the one used by Tapestry, to know about its mapping.

This changes the servlet container to only forward requests inside the `t5app` folder to Tapestry.
Requests for other folders (or the root folder) will not be passed to Tapestry at all.
The symbol contribution informs Tapestry to change the URLs it generates to include the necessary folder name.
It also affects the logic in Tapestry that recognizes and handles requests.

In addition, if you choose to place page template files in the context, rather than on the classpath (as with component templates), then you will place those template files inside the `t5app` folder.

At this time, it is still not possible to run multiple Tapestry 5 applications within the same web application.
