= Cascading Style Sheets (CSS)

Most web applications delegate to Cascading Style Sheets (CSS) the stylistic details of the page – fonts, colors, margins, borders and alignment.
This helps the remaining HTML to remain simple and semantic, which usually makes it easier to read and maintain.

Tapestry includes sophisticated support for CSS in the form of annotation-based linking, far-future expire headers, automatic duplicate removal, and other features provided for assets.

== Default style sheet
Tapestry includes a built-in style sheet, `tapestry.css`, in all HTML documents (documents that have an outer `<html>` element and a nested `<head>` element), as part of the `core` JavaScript stack.


== Adding your own CSS
A page or component (for example, a xref:layout-component.adoc[layout component]) that is rendering the `<head>` tag can add a style sheet directly in the markup.

[source,xml]
----
<head>
  <link href="/css/site.css" rel="stylesheet" type="text/css"/>
  ...
----

If you want to leverage Tapestry's xref:localization.adoc[localization support], you may want to make use of an expansion and the `asset:` or `context:` binding prefix:

[source,xml]
----
<head>
  <link href="${context:css/site.css}" rel="stylesheet" type="text/css"/>
  ...
----

The `context:` prefix means that the remainder of the expansion is a path to a context asset, a resource in the web application root (`src/main/webapp` in your workspace).
By contrast, the `asset:` prefix tells Tapestry to look in the classpath. See xref:assets.adoc[].

== Using the @Import annotation
Another approach to adding a style sheet is to include an javadoc:org.apache.tapestry5.annotations.Import[label=@Import] annotation on your component class:

.MyComponent.java
[source,java]
----
@Import(stylesheet="context:css/site.css")
public class MyComponent
{

}
----

As with xref:client-side-javascript.adoc[included JavaScript libraries], each style sheet will only be added once, regardless of the number of components that include it via the annotation.

== Conditionally loading IE-only style sheets
If you need to load a different style sheet for Internet Explorer browsers, or for certain versions of IE browsers, you can use Tapestry's built-in support for IE conditional comments.
Just add something like the following to your page or component (or layout) class:

[source,java]
----
@Environmental
private JavaScriptSupport javaScriptSupport;
     
@Inject @Path("context:layout/ie-only.css")
private Asset ieOnlyStylesheet;

// add an IE-only style sheet if browser is IE
void afterRender() {
    javaScriptSupport.importStylesheet(
        new StylesheetLink(ieOnlyStylesheet,
        new StylesheetOptions(null, "IE"))
    );
}
----

The above will render something like:

[source,html]
----
<!--[if IE]>
<link type="text/css" rel="stylesheet" href="/assets/1.0-SNAPSHOT/ctx/layout/ie-only.css"></link>
<![endif]-->
----

Naturally, the conditional part can be any other IE http://en.wikipedia.org/wiki/Conditional_comment[conditional expression], such as "lt IE 8".

== Suppressing the default style sheet
Though it should be rarely needed, you can prevent Tapestry's default style sheet from loading by overriding the configuration in your application's module (normally `AppModule.java`):

.AppModule.java (partial)
[source,java]
----
@Contribute(MarkupRenderer.class)
public static void deactiveDefaultCSS(OrderedConfiguration<MarkupRendererFilter> configuration)
{
    configuration.override("InjectDefaultStylesheet", null); <1>
}
----
<1> In previous releases the configuration key was unfortunately misspelled (missing the 's' in 'sheet'). This was fixed in Tapestry 5.3.

