= Download

Tapestry can be downloaded from various places, described below, in either binary or source format.

== Using a Build Tool
The easiest way is to download Tapestry and its dependencies from the https://repo1.maven.org/maven2/[Maven Central Repository], leveraging a build tool such as https://maven.apache.org/[Apache Maven], https://www.gradle.org/[Gradle] etc.
Just declare a dependency on Tapestry (see below for sample dependency declararions) and let the build tool take care of downloading the necessary files to your local machine. 

.Maven: Dependency on Tapestry to be added to your `pom.xml`
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>org.apache.tapestry</groupId>
  <artifactId>tapestry-core</artifactId>
  <version>{tapestry-version}</version>
</dependency>
----

.Gradle: Dependency on Tapestry to be added to your `build.gradle`
[source,gradle,subs="+attributes"]
----
implementation 'org.apache.tapestry:tapestry-core:{tapestry-version}'
----


== Getting ZIP files
Binaries, source code, and Javadocs are also available as a zip archive from the https://downloads.apache.org/tapestry/[Apache Distribuction Directory] (current and more recent releases) and from the https://archive.apache.org/dist/tapestry/[Apache Archive Site] (older releases). 

Here are the direct links to the latest release, Tapestry {tapestry-version}:

[cols="1,3"]
|===
|Binaries
|https://downloads.apache.org/tapestry/apache-tapestry-{tapestry-version}-bin.zip[zip]
( https://downloads.apache.org/tapestry/apache-tapestry-{tapestry-version}-bin.zip.asc[asc], https://downloads.apache.org/tapestry/apache-tapestry-{tapestry-version}-bin.zip.sha256[sha256] )

|Source
|https://downloads.apache.org/tapestry/apache-tapestry-{tapestry-version}-sources.zip[zip]
( https://downloads.apache.org/tapestry/apache-tapestry-{tapestry-version}-sources.zip.asc[asc], https://downloads.apache.org/tapestry/apache-tapestry-{tapestry-version}-sources.zip.sha256[sha256] )

|Javadoc
|https://downloads.apache.org/tapestry/apache-tapestry-{tapestry-version}-apidocs.zip[zip]
( https://downloads.apache.org/tapestry/apache-tapestry-{tapestry-version}-apidocs.zip.asc[asc] )
|===

The signature (`.asc`) and the checksum (`.sha256`) are provided for you to be able to verify the integrity of the archive file (`.zip`).

== Using the Version Control System (Git, SVN)
The source code can also be checked out anonymously from either Apache GitBox or GitHub with the `git clone` command:

.Apache GitBox
----
git clone https://gitbox.apache.org/repos/asf/tapestry-5.git
----

.GitHub
----
git clone https://github.com/apache/tapestry-5.git
----

Versions 5.3.2 and earlier are also available via https://subversion.apache.org/[Apache Subversion].

----
svn checkout https://svn.apache.org/repos/asf/tapestry/tapestry5/trunk/
----
