= The Apache Tapestry User Guide
:navtitle: Introduction

Welcome to the User Guide for Tapestry {page-component-display-version}. Hopefully it provides the information you are looking for. For additional sources of information, see the xref:main::documentation.adoc[] overview.

[sidebar]
If you see anything in the User Guide that is not correct or poorly described, please feel invited to suggest an improvement, ideally through a GitHub Pull Request.

== Prerequisites
This User Guide assumes you:

* have a general understanding of how the Web works, especially the interplay of requests and responses as specified in the https://httpwg.org[Hypertext Transport Protocol (HTTP)];
* know basic Java;
* are familiar with the https://docs.oracle.com/javaee/7/tutorial/servlets.htm[Java Servlet Technology];
* understand that Web browsers display pages based on input expressed in https://www.w3.org/TR/html/[Hypertext Markup Language (HTML)] and related technologies such as https://www.w3.org/TR/CSS21/[Cascading Style Sheets (CSS)] and https://developer.mozilla.org/docs/Web/JavaScript[JavaScript].


== What is Apache Tapestry?
Apache Tapestry is an open-source framework for creating dynamic, robust, highly scalable web applications in Java.
Tapestry complements and builds upon the standard Java Servlet API, and so it works in any servlet container or application server.

Tapestry divides a web application into a set of pages, each constructed from components.
This provides a consistent structure, allowing the Tapestry framework to assume responsibility for key concerns such as URL construction and dispatch, persistent state storage on the client or on the server, user input validation, localization/internationalization, and exception reporting.
Developing Tapestry applications involves creating HTML templates using plain HTML, and adding a small java class for each.
In Tapestry, you create your application in terms of objects, and the methods and properties of those objects – and specifically not in terms of URLs and query parameters.
Tapestry brings true object oriented development to Java web applications.

Tapestry is specifically designed to make creating new components very easy, as this is a routine approach when building applications.

Tapestry is architected to scale from tiny, single-page applications all the way up to massive applications consisting of hundreds of individual pages, developed by large, diverse teams. Tapestry easily integrates with any kind of backend, including JEE, Spring and Hibernate.

It's more than what you can do with Tapestry ... it's also how you do it!
Tapestry is a vastly productive environment. Java developers love it because they can make Java code changes and see them immediately ... no redeploy, no restart!
And it's blazingly fast to boot (even when files have changed).
Designers love it because Tapestry templates are so close to ordinary HTML, without all the cruft and confusion seen in JavaServer Pages.
Managers love it because it makes it easy for large teams to work together productively, and because they know important features (including localization) are baked right in.
Once you work in Tapestry there's no going back!

Tapestry is released under the Apache Software License 2.0.

== Tapestry as a Java Servlet Filter
Tapestry integrates with the Java Servlet API by implementing https://docs.oracle.com/javaee/7/api/javax/servlet/Filter.html[javax.servlet.Filter].
Similar to servlets, filters are added to a web application in the deployment descriptor (`web.xml`).

.web.xml (partial)
[source,xml]
----
<web-app>
...
    <filter>
        <filter-name>app</filter-name>
        <filter-class>org.apache.tapestry5.TapestryFilter</filter-class> 
    </filter>
...
</web-app>
----

javadoc:org.apache.tapestry5.TapestryFilter[] is the entry point to Tapestry.
Inside Tapestry, various request handlers and a various dispatchers control access to (your) pages, components and static assets.
The diagram below is intended as a rough overview of how Tapestry xref:request-processing.adoc[processes requests].

.Sequence Diagram of Tapestry (partial)
[plantuml,tapestry-sequence,svg,role=sequence]
----
include::partial$diagrams/tapestry-sequence.puml[]
----

The request handlers and dispatchers are organized in pipelines and chain of commands, making it very easy to configure or extend Tapestry to your needs.
That said, Tapestry embraces the _convention over configuration_ principle, allowing you to build great web applications with only minimal configuration and without the need to extend anything.


== Tapestry and Inversion-of-Control (IoC)
Tapesty features an Inversion of Control (IoC) container.
IoC is a design approach that allows a working system to be fabricated from many small, easily testable pieces.

It is also possible to run the IoC container independently from the Java Servlet API
This is useful for xref:integration-testing.adoc[].


