= Page Navigation

In essence, a Tapestry application is a number of related pages, working together.
To some degree, each page is like an application unto itself.

Any individual request will be targeted at a single page.
Requests come in two forms: 

* _component event_ requests target a specific component on a specific page, triggering an event within that component
* _render requests_ target a specific page, and stream the HTML markup for that page back to the client

This dichotomy between component event requests and render requests alleviates a number of problems in traditional web applications related to the browser back button, or to the user hitting the refresh button in their browser.

== Logical Page Name Shortening
In certain cases, Tapestry will shorten the the logical name of a page.
For example, the page class `org.example.pages.address.CreateAddress` will be given a logical name of `address/Create` (the redundant `Address` is removed as a suffix).
However, this only affects how the page is referenced in URLs; the template file will still be `CreateAddress.tml`, whether on the classpath, or as `address/CreateAddress.tml` (in the web context).

Tapestry actually creates multiple names for the name page: `address/Create` and `address/CreateAddress` are both synonymous.
You can user either in Java code that refers to a page by name, or as the page parameter of a `PageLink`.

== Component Event Requests & Responses
Main Article: xref:component-events.adoc[]

Component event requests may take the form of hyperlinks (javadoc:org.apache.tapestry5.corelib.components.EventLink[] or javadoc:org.apache.tapestry5.corelib.components.ActionLink[]) or form submissions (javadoc:org.apache.tapestry5.corelib.components.Form[]).

The value returned from an event handler method controls the response sent to the client web browser.

The URL for a component event request identifies the name of the page, the nested id of the component, and the name of the event to trigger on the component (specified by the `event` parameter of `EventLink`, or `action` for an `ActionLink`).
Further, a component event request may contain additional context information, which will be provided to the event handler method.

These URLs expose a bit of the internal structure of the application.
Over time, as an application grows and is maintained, the ids of components may change.
This means that component event request URLs should not be bookmarked.
Fortunately, users will rarely have the chance to do so (see below).

=== Null Response
If the event handler method returns no value, or returns null, then the current page (the page containing the component) will render the response.

A page render URL for the current page is created and sent to the client as a client side redirect.
The client browser will automatically submit a new request to generate the page.

The user will see the newly generated content in their browser.
In addition, the URL in the browser's address bar will be a render request URL.
Render request URLs are shorter and contain less application structure (for instance, they don't include component ids or event types).
Render requests URLs are what your users will bookmark.
The component event request URLs are transitory, meaningful only while the application is actively engaged, and not meant to be used in later sessions.

[source,java]
----
public Object onAction(){
  return null;
}
----

=== String Response
When a string is returned, it is expected to be the logical name of a page (as opposed to the page's fully qualified class name).
As elsewhere, the name of the page is case insensitive.

Again, a render request URL will be constructed and sent to the client as a redirect.

[source,java]
----
public String onAction(){
  return "Index";
}
----

=== Class Response
When a class is returned, it is expected to be a page class.
Returning a page class from an event handler is safer for refactoring than returning a page name.

As with other response types, a render request URL will be constructed and sent to the client as a redirect.

[source,java]
----
public Object onAction(){
  return Index.class
}
----

=== Page Response
You may also return an instance of a page, rather than the name or class of a page.

A page may be injected via the javadoc:org.apache.tapestry5.annotations.InjectPage[label=@InjectPage] annotation.

Often, you will configure the page in some way before returning the page (examples below).

You can also return a component within the page, but this will generate a runtime warning (unless you are doing a partial-page update via Ajax).

[source,java]
----
@InjectPage
private Index index;

public Object onAction(){
  return index;
}
----

=== Http Error
An event handler method may return an instance of javadoc:org.apache.tapestry5.services.HttpError[] to send an error response to the client.

[source,java]
----
public Object onAction(){
  return new HttpError(302, "The Error message);
}
----

=== Link Response
An event handler method may return a javadoc:org.apache.tapestry5.http.Link[] instance directly.
The `Link` is converted into a URL and a client redirect to that URL is sent to the client.

The javadoc:org.apache.tapestry5.ComponentResources[] object that is injected into your pages (and components) has methods for creating component links.

The javadoc:org.apache.tapestry5.services.PageRenderLinkSource[] service can be injected to allow links to other pages to be created (though that is rarely necessary, given the other options listed above).

=== Stream Response
An event handler can also return a javadoc:org.apache.tapestry5.StreamResponse[] object, which encapsulates a stream to be sent directly to the client browser.
This is useful for components that want to, say, generate an image or PDF and provide it to the client:

[source,java]
----
public Object onAction(){
    return new StreamResponse() {
        @Override
        public String getContentType() {
            return "application/pdf";
        }
        @Override
        public InputStream getStream() throws IOException {
            return new ByteArrayInputStream(getMyPdfByteArray());
        }
        @Override
        public void prepareResponse(Response response) {
            response.setHeader("Content-Disposition", "attachment; filename=\"" + myFileName + "\"");
        }
    };
}
----

=== URL Response
A `java.net.URL` response is handled as a client redirect to an external URL.

=== Object Response
Any other type of object returned from an event handler method is an error.



== Page Render Requests
Render requests are simpler in structure and behavior than component event requests.
In the simplest case, the URL is simply the logical name of the page.

Pages may have an activation context.
The activation context represents persistent information about the state of the page.
In practical terms, the activation context is usually the id of some database-persistent object.

When a page has an activation context, the values of the context are appended to the URL path.
For example, in `http://www.example.com/myapp/foo/bar` the `myapp` part is the servlet context (usually the name of your app), and the `foo/bar` part is the activation context, with `foo` being the first activation parameter and `bar` being the second.

It is common for most pages to not have any activation context.

The activation context may be explicitly set when the render request link is created (the javadoc:org.apache.tapestry5.corelib.components.PageLink[] component has a context parameter for this purpose).

When no explicit activation context is provided, the page itself is queried for its activation context.
This querying takes the form of an event trigger.
The event name is "passivate" (as we'll see shortly, there's a corresponding "activate").
The return value of the method is used as the context. For example:

[source,java]
----
public class ProductDetail
{
  private Product product;
  ...
  long onPassivate() { return product.getId(); }
}
----

The activation context may consist of a series of values, in which case the return value of the method should be an array or a `List`.

[NOTE]
====
If you are using the `tapestry-hibernate` integration library and your passivate context is a Hibernate entity, then you can just use the entity itself, not its id.
Tapestry will automatically extract the entity's id into the URL, and convert it back for the "activate" event handler method.
====

=== Page Activation
When a page render request arrives, the page is _activated_ before it is rendered.

Activation serves two purposes:
* It allows the page to restore its internal state from data encoded into the URL (the activation context discussed above).
* It provides coarse approach to validating access to the page.

The later case – validation – is generally concerned with user identity and access; if you have pages that may only be accessed by certain users, you may use the page's activate event handler for verifying that access.

Page activation uses Tapestry's _Component Event_ mechanism. See xref:component-events.adoc[] for details.

A page's activate event handler mirrors its passivate handler:

[source,java]
----
private Product product;
// ...
void onActivate(long productId)
{
   product = productDAO.getById(productId);
}
// ...
----

Here's the relevant part: when the page renders, it is likely to include more component event request URLs (links and forms).
The component event requests for those links and forms will also start by activating the page, before performing other work.
This forms an unbroken chain of requests that include the same activation context.

To some degree, this same effect could be accomplished using a xref:persistent-page-data.adoc[persistent page value], but that requires an active servlet session, and the result is not bookmarkable.

Your activate event handler, like any event handler, may also return a value, which is treated identically to a return value of a component event method. This technique is commonly used as a simple access validation mechanism.

You sometimes need to handle multiple page activation scenarios in one page class.
You could create multiple activate event handler methods with different arguments (see the xref:component-events.adoc#_multiple_method_matches[Multiple Method Matches] for details), but if you do so, you should generally return `true` from each to avoid having more than one activation event handler method from being called for each page request.
However, a better approach is to create one method with an EventContext argument.
Tapestry will populate the EventContext argument with all of the activation parameters, and the javadoc:org.apache.tapestry5.EventContext[]'s `get` method will retrieve and coerce each parameter to the desired type. For example:

[source,java]
----
void onActivate(EventContext eventContext) {

  String color = DEFAULT_COLOR;

  if (eventContext.getCount() > 0) {
    long productId = eventContext.get(Long.class, 0);

    if (eventContext.getCount() > 1) {
      String color = eventContext.get(String.class, 1);
    }
    product = productDAO.getById(productId, color);
  } else {
    return SelectProduct.class; // no product selected
  }
}
----

== Page Navigation Patterns

This combination of action links and context and page context can be put together in any number of ways.

Let's take a typical master/detail relationship using the concept of a product catalog page.
In this example, the `ProductListing` page is a list of products, and the `ProductDetails` page must display the details for a specific product.

=== Pattern 1: Component event requests / Persistent Data
In this pattern, the `ProductListing` page uses action events and a persistent field on the `ProductDetails` page.

.ProductListing.tml
[source,xml]
----
<t:loop source="products" value="product">
  <a t:type="actionlink" t:id="select" context="product.id">${product.name}</a>
</t:loop>
----

.ProductListing.java
[source,java]
----
@InjectPage
private ProductDetails details;

Object onActionFromSelect(long productId)
{
  details.setProductId(productId);

  return details;
}
----

.ProductDetails.java
[source,java]
----
@Inject
private ProductDAO dao;

private Product product;

@Persist
private long productId;

public void setProductId(long productId) { this.productId = productId; }

void onActivate()
{
  product = dao.getById(productId);
}
----

This is a minimal approach, perhaps good enough for a prototype.

When the user clicks a link, the component event request URL will initially be something like `http://.../productlisting.select/99` and the final render request URL will be something like `http://.../productdetails`.
Notice that the product id (`99`) does not appear in the render request URL.

This pattern has the following drawbacks:

* It requires a session (to store the productId field between requests).
* It may fail if the `ProductDetails` page is accessed before a valid product id is set.
* The URL does not indicate the identity of the product; if the user bookmarks the URL and comes back later, they will trigger the previous case (no valid product id).

=== Pattern 2: Component Event Requests / No Persistent Data
We can improve the previous example without changing the `ProductListing` page, using a passivation and activation context to avoid the session and make the links more bookmarkable.

.ProductDetails.java
[source,java]
----
@Inject
private ProductDAO dao;

private Product product;

private long productId;

public void setProductId(long productId) { productId = productId; }

void onActivate(long productId)
{
  this.productId = productId;

  product = dao.getById(productId);
}

long onPassivate() { return productId; }
----

This change ensures that the render request URL will include the product id, i.e., `http://.../productdetails/99`.

It has the advantage that the connection from page to page occurs in type-safe Java code, inside the `onActionFromSelect` method of `ProductListing`.
It has the disadvantage that clicking a link requires two round trips to the server.

=== Pattern 3: Render Requests Only
This is the most common version of this master/detail relationship.

.ProductListing.tml
[source,xml]
----
<t:loop source="products" value="product">
  <a t:type="pagelink" page="productdetails" context="product.id">${product.name}</a>
</t:loop>
----

.ProductListing.java
[source,java]
----
// No code is needed to support the link.
----

.ProductDetails.java
[source,java]
----
@Inject
private ProductDAO dao;

private Product product;

private long productId;

void onActivate(long productId)
{
  this.productId = productId;

  product = dao.getById(productId);
}

long onPassivate() { return productId; }
----

The `setProductId()` method is no longer needed.

== Limitations
As your application's workflow expands, you may find that there is not a reasonable way to avoid storing some data persistently between requests, outside of the page activation context.
For example, if from the `ProductDetails` page, the user is allowed to navigate to related pages and then back to `ProductDetails`, it starts to become necessary to keep passing that product id around from page to page to page.

At some point, persistent values make more sense.
Tapestry has several persistence strategies available, including one that stores data in URL query parameters.
See xref:persistent-page-data.adoc[] for details.
