= Security

Tapestry has a number of security features designed to harden your application against unwanted intrusion and denial of service.

== HTTPS-only Pages
Main Article: xref:https.adoc[]

Tapestry provides several annotations and configuration settings that you can use to ensure that all access to certain pages (or all pages) occurs only via the encrypted HTTPS protocol.
See xref:https.adoc[] for details.

== Controlling Page Access
For simple access control needs, you can contribute a javadoc:org.apache.tapestry5.services.ComponentRequestFilter[] with your custom logic that decides which pages should be accessed by which users.
The Tapestry Hotel Booking app demonstrates this approach with an `@AnonymousAccess` annotation along with a `ComponentRequestFilter` named `AuthenticationFilter.java`.
The filter enforces security by intercepting all requests to pages that don't have that annotation, and it redirects those requests to the login page.
https://tapestry-jumpstart.org/jumpstart/examples/infrastructure/protectingpages[JumpStart] has a similar demo.

For more advanced needs see the Security Framework Integration section below.

== White-listed Pages
Pages whose component classes are annotated with javadoc:org.apache.tapestry5.annotations.WhitelistAccessOnly[label=@WhitelistAccessOnly] will only be displayed to users (clients) that are on the _whitelist_.
By default, the whitelist consists only of clients whose fully-qualified domain name is "localhost" (or the IP address equivalent, 127.0.0.1 or 0:0:0:0:0:0:0:1), but you can customize this by contributing to the javadoc:org.apache.tapestry5.services.security.ClientWhitelist[] service in your application's module class (usually `AppModule.java`):

.AppModule.java (partial) – simple inline example
[source,java]
----
@Contribute(ClientWhitelist.class)
public static void provideWhitelistAnalyzer(OrderedConfiguration<WhitelistAnalyzer> configuration)
{
    configuration.add("MyCustomAnalyzer", new WhitelistAnalyzer()
    {
        public boolean isRequestOnWhitelist(Request request)
        {
            // add your custom logic here and return true or false
            return true;
        }
    }, "before:*");
}
----

Sometimes, in production, a firewall or proxy may make it look like the client web browser originates from localhost, with the consequence that whitelisted pages may be visible to all users.
See the Security FAQ for how to deal with this.

== Asset Security
Tapestry serves assets (static content such as CSS files, images, and JavaScript, many of which are on the classpath alongside your compiled class files) to the client.
Because of this, great care has gone into ensuring that certain file types cannot be served to the client.
By default, file ending with `.class`, `.tml` and `.properties` can be served to the client only if the request includes the file's MD5 checksum.
As you would expect, that blacklist can be extended.
See xref:assets.adoc[] for more information.

== Cross Site Request Forgery (CSRF)
Cross Site Request Forgery is a type of security vulnerability in which legitimate, authorized users may be made to unwittingly submit malicious requests to your web application.

https://github.com/porscheinformatik/tapestry-csrf-protection[Tapestry-csrf-protection] is a 3rd party module that has several features for preventing CSRF attacks.
It protects all component event handlers (event links, forms, etc.) by adding a CSRF token to event links and adds a CSRF token as a hidden field to all forms.
Tokens are generated on a per-session basis.

== Security Framework Integration
Tapestry does not lock you into a specific authentication/authorization implementation.
There are integration modules available for the more popular open source Java security frameworks.
A popular choice among Tapestry users is http://www.tynamo.org/tapestry-security+guide/[tapestry-security (based on Apache Shiro) from Tynamo.org].
It is always kept up-to-date with the latest Tapestry versions and offers several supporting security modules (e.g. http://www.tynamo.org/tapestry-security-jpa+guide/[tapestry-security-jpa], http://www.tynamo.org/tynamo-federatedaccounts+guide/[tynamo-federatedaccounts]).
