= Session Storage

Most web applications will need to have some data that is shared across multiple pages.
Perhaps you are creating a multi-page wizard, or you have an object that tracks the user's identify once logged in, or maybe you need to manage a shopping cart.

Ordinary xref:persistent-page-data.adoc[page-persistent fields] won't work for this, since persistent fields are available only to a specific page, not shared across multiple pages.

Tapestry provides a mechanism for storing such data Session State Objects.

== Application State Objects
With a Application State Object (ASO), the value is automatically stored outside the page.
With the default storage strategy, it is stored in the session.
Such a value is global to all pages for the same user, but is stored separately for different users.

A field holding an ASO is marked with the javadoc:org.apache.tapestry5.annotations.ApplicationState[label=@ApplicationState] annotation.

[source,java]
----
public class MyPage
{
  @ApplicationState
  private ShoppingCart shoppingCart;
  
  //  ...
}
----

Any other component or page that declares a field of the same type, regardless of name, and marks it with the `@ApplicationState` annotation will share the same value.
It's that simple.
However, using `@ApplicationState` safely requires care:

IMPORTANT: DO NOT USE `@ApplicationState` FOR SIMPLE TYPES! Only use it on variables that are of a custom-built class designed expressly for this purpose!
See the <<Pitfalls>> section below.

The first time you access an ASO, it is created automatically.
Typically, the ASO will have a public no-args constructor ... but you may inject dependencies into the ASO via its constructor, as you can with a Tapestry IoC service implementation.

NOTE: For Tapestry 4 Users: a big change here is that you don't need to provide any configuration for the ASO before using it, nor do you provide a logical name.
Tapestry 5 uses the class name to identify the ASO, so there's no need for a logical name.

Assigning a value to an ASO field will store that value.
Assigning null to an ASO field will remove the ASO (reading the field subsequently will force a new ASO instance to be created).

=== Pitfalls
With `@ApplicationState`, you are creating a session-wide data storage area that is tied to the _type_ (class) of the variable you annotate.
It is not specifically tied to the variable itself, or even to the class in which that variable was annotated.
As with all session data, there is the serious possibility of collisions, not just within your application but with other modules/libraries:

[source,java]
----
@ApplicationState
private String userName; <1>

// ... then, later in this class or any other:

@ApplicationState
private String userCity; <2>
----
<1> Unsafe - `String` is not a custom type
<2> This overwrites value in `userName`, because it's also a `String`!

The simple rule is, NEVER use `@ApplicationState` for simple-type variables.
It is ALWAYS worth taking the time to build a special class to hold your session state information.
Doing so will force you to consolidate that information into a single, logical unit that can't be accidentally accessed by other classes.

=== Check for Creation
Scalable web applications do not create the server-side session needlessly.
If you can avoid creating the session, especially on first access to your web application, you will be able to handle an order of magnitude more users.
So, if you can avoid creating the ASO, you should do so.

But how to avoid creating it?
Simply checking (`shoppingCart != null`) will force the creation of the SSO and the session to store it in.

Instead, create a second field with a matching name but with `Exists` appended:
[source,java]
----
private boolean shoppingCartExists;
----

It is not annotated; it is located by naming convention ("Exists" appended).
It must be type boolean and must be a private instance variable.
Tapestry will automatically set this variable to true when the ASO is created, so you can check it to see if the ASO already exists.

Alternately, you may allow for the state being null:

[source,java]
----
@ApplicationState(create=false)
private ShoppingCart shoppingCart;
----

In this case, the `shoppingCart` field will be null if the `ShoppingCart` ASO does not exist, but will be non-null if it has been created (either by assigning a value to the field, or by a different ASO field where create is true).

=== Persistence Strategies
Main Article: xref:persistent-page-data.adoc[]

Each ASO is managed according to a persistence strategy.
The default persistence strategy, `session`, stores the ASOs inside the session.
The session is created as needed.

=== Configuring ASOs
Generally, you will need to configure your ApplicationState Object if you want to change the persistence strategy to other than the default.
(Right now there's only one built in strategy, but more will be coming in the future.)

Alternately, you can configure a Application State Object in order to control how it is instantiated.
You may need to inject some values into the ASO when it is first created, or otherwise initialize it.
In this case, you may provide an javadoc:org.apache.tapestry5.services.ApplicationStateCreator[] object, which will be called upon to create the ASO as necessary.
This is also the technique to use when you want your ASO to be represented by an interface rather than a class: you need to provide a creator that knows about the class that implements the interface.

A Application State Object is configured using contributions to the javadoc:org.apache.tapestry5.services.ApplicationStateManager[] service.
From your application's module:

[source,java]
----
public void contributeApplicationStateManager(MappedConfiguration<Class, ApplicationStateContribution> configuration)
{
  ApplicationStateCreator<MyState> creator = new ApplicationStateCreator<ShoppingCart>()
  {
    public ShoppingCart create()
    {
      return new ShoppingCart(new Date());
    }
  };
  
  configuration.add(ShoppingCart.class, new ApplicationStateContribution("session", creator));
}
----

Here, we have an ASO type of ShoppingCart, and we're providing a creator for it.
We've dolled the creator up with some generic types, but that isn't essential.

Our creator creates a new `MyState` instance using an alternate constructor that takes the current date and time.
Again, just an example.

Finally, we create an javadoc:org.apache.tapestry5.services.ApplicationStateContribution[] identifying the strategy name and the creator, and give that to the configuration.

